<?php

/**
 * @file
 * Contains zipang_config.module.
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_alter().
 */
function zipang_config_form_system_site_maintenance_mode_alter(array &$form, FormStateInterface $form_state, $form_id) {

    // config for maintenance mode enabled pages
    $maintenance_mode_enabled_pages = \Drupal::config('zipang_config.maintenance')->get('maintenance_mode_enabled_pages');
    $soft_maintenance_mode = \Drupal::config('zipang_config.maintenance')->get('soft_maintenance_mode');
    $form['advanced'] = [
      '#type' => 'vertical_tabs',
      '#title' => t('Put site into Soft Maintenance Mode'),
    ];
    $form['soft_maintenance_details'] = [
      '#type' => 'details',
      '#group' => 'advanced',
      '#title' => t('Soft Maintenance Configuration'),
    ];

    $form['soft_maintenance_details']['soft_maintenance_mode'] = [
        '#type' => 'checkbox',
        '#title' => t('Put site into soft maintenance mode'),
        '#default_value' => $soft_maintenance_mode,
      ];

    $form['soft_maintenance_details']['maintenance_mode_enabled_pages'] = [
        '#type' => 'textarea',
        '#title' => t('Pages listed here will be redirected to maintenance page.'),
        '#default_value' => $maintenance_mode_enabled_pages,
        '#resizable' => t('vertical'),
        '#description' => t('Specify pages by using their paths. Enter one path per line.
        The * character is for all pages. An example path is /promotions, /about-us, /faq/privacy etc.'),
    ];

    $form['#submit'][] = 'maintenance_alter_submit';
}

function maintenance_alter_submit(array $form, FormStateInterface $form_state) {
    \Drupal::configFactory()->getEditable('zipang_config.maintenance')
      ->set('maintenance_mode_enabled_pages', $form_state->getValue('maintenance_mode_enabled_pages'))
      ->save();

    \Drupal::configFactory()->getEditable('zipang_config.maintenance')
      ->set('soft_maintenance_mode', $form_state->getValue('soft_maintenance_mode'))
      ->save();
}

/**
 * Implements hook_form_alter().
 */
function zipang_config_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // specifically for webcomposer form manager list alter expanding row delta range
  if ($form['#form_id'] == 'webcomposer_form_manager.manage_form') {
    foreach ($form['table'] as $key => $value) {
      if (empty(strpos($key, '#')) && strpos($key, '#') !== 0) {
        $form['table'][$key]['weight']['#delta'] = 50;
      }
    }
  }
}