<?php

/**
 * @file
 * Contains mobile_live_dealer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_live_dealer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mobile_live_dealer module.
    case 'help.page.mobile_dealer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Live Dealer configuration module') . '</p>';
      return $output;

    default:
  }
}
