<?php

/**
 * @file
 * Contains msw_front_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function msw_front_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the msw_front_blocks module.
    case 'help.page.msw_front_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for msw home blocks.') . '</p>';
      return $output;

    default:
  }
}
