<?php

/**
 * @file
 * Contains games_page_loading.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function games_page_loading_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the games_page_loading module.
    case 'help.page.games_page_loading':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Games Search Recommendation Module') . '</p>';
      return $output;

    default:
  }
}