<?php

/**
 * @file
 * Contains mobile_nextbet.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_nextbet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mobile_nextbet module.
    case 'help.page.mobile_nextbet':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mobile Nextbet configuration') . '</p>';
      return $output;

    default:
  }
}
