<?php

/**
 * @file
 * Contains webcomposer_right_side_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webcomposer_right_side_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_right_side_block module.
    case 'help.page.webcomposer_right_side_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows to add Inner page right side block') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function webcomposer_right_side_block_theme() {
  return [
    'webcomposer_right_side_block' => [
      'template' => 'webcomposer_right_side_block',
      'render element' => 'children',
    ],
  ];
}
