<?php

/**
 * @file
 * Contains zipang_mobile_games.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zipang_mobile_games_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zipang_mobile_games module.
    case 'help.page.zipang_mobile_games':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Zipang Mobile Games') . '</p>';
      return $output;

    default:
  }
}
