<?php

/**
 * @file
 */

/**
 * Implements hook_webcomposer_form_validation_alter().
 *
 * Registration form custom validation.
 */
function registration_form_webcomposer_form_validation_alter(&$validations) {
  $validations['username_availability'] = [
    'title' => 'Username Availability',
    'description' => 'Validate username if already exist',
    'error' => 'Username not available',
  ];
  $validations['email_avilability'] = [
    'title' => 'Email Availability',
    'description' => 'Validate user email if already exist',
    'error' => 'Email not available',
  ];
}
