<?php

/**
 * @file
 * Contains mobile_marketing_space.module.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\TranslatableInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_marketing_space_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mobile_marketing_space module.
    case 'help.page.mobile_marketing_space':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mobile Marketing Space configuration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Form alter for webcomposer_slider_v2 section.
 */
function mobile_marketing_space_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $forms = [
    'mobile_marketing_space_add_form',
    'mobile_marketing_space_edit_form',
  ];
  if (in_array($form_id, $forms)) {
    $form['#validate'][] = 'mobile_marketing_space_validate';
  }
}

/**
 * Form validation for mobile_marketing_space required fields.
 */
function mobile_marketing_space_validate(&$form, FormStateInterface $form_state) {
  $publish = $form_state->getValue('field_publish_date');
  $unpublish = $form_state->getValue('field_unpublish_date');
  $loginState = $form_state->getValue('field_log_in_state');
  $bannerImage = $form_state->getValue('field_banner_image_portrait');
  $bannerImagePost = $form_state->getValue('field_post_banner_image_portrait');
  $bannerImageLandscape = $form_state->getValue('field_banner_image_landscape');
  $bannerImagePostLandscape = $form_state->getValue('field_post_banner_image_landscap');

  $publishDate = isset($publish[0]['value']) ? $publish[0]['value']->format('U') : NULL;
  $unpublishDate = isset($unpublish[0]['value']) ? $unpublish[0]['value']->format('U') : NULL;

  if ($unpublishDate && $unpublishDate < $publishDate) {
    $form_state->setErrorByName('field_unpublish_date', t('Unpublish date should be greater than the publish date.'));
  }

  if ($loginState[0]['value'] == 0 && $bannerImage[0]['fids'] == NULL) {
    $form_state->setErrorByName('field_banner_image_portrait', t('Pre Banner Image Portrait field is required.'));
  }

  if ($loginState[0]['value'] == 0 && $bannerImageLandscape[0]['fids'] == NULL) {
    $form_state->setErrorByName('field_banner_image_landscape', t('Pre Banner Image Landscape field is required.'));
  }

  if ($loginState[1]['value'] == 1 && $bannerImagePost[0]['fids'] == NULL) {
    $form_state->setErrorByName('field_post_banner_image_portrait', t('Post Banner Image Portrait field is required.'));
  }

  if ($loginState[1]['value'] == 1 && $bannerImagePostLandscape[0]['fids'] == NULL) {
    $form_state->setErrorByName('field_post_banner_image_landscap', t('Post Banner Image Landscape field is required.'));
  }
}
