<?php

/**
 * @file
 * Contains msw_prioritization_menu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function msw_prioritization_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the msw_prioritization_menu module.
    case 'help.page.msw_prioritization_menu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Left Menu Entity for video call prioritization menu') . '</p>';
      return $output;

    default:
  }
}
