<?php

/**
 * @file
 * Contains luckybaby_dropdown_menu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function luckybaby_dropdown_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the luckybaby_dropdown_menu module.
    case 'help.page.luckybaby_dropdown_menu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dropdown Menu') . '</p>';
      return $output;

    default:
  }
}
