<?php

/**
 * Implements hook_uninstall
 */
function webcomposer_dropdown_sportslist_uninstall() {
  $keys = [
    'webcomposer_dropdown_menu.dropdown_menu.section.sportslist',
    'webcomposer_dropdown_menu.dropdown_menu.section.contentwidget',
    'webcomposer_dropdown_menu.dropdown_menu.section.contentwysiwygwidget',
  ];

  foreach ($keys as $key) {
    \Drupal::configFactory()->getEditable($key)->delete();
  }
}
