<?php

/**
 * Implements hook_uninstall
 */
function webcomposer_dropdown_sportslist_uninstall() {
  $keys = [
    'webcomposer_dropdown_menu.dropdown_menu.section.sports_list',
    'webcomposer_dropdown_menu.dropdown_menu.section.content_widget',
    'webcomposer_dropdown_menu.dropdown_menu.section.content_wysiwyg_widget',
  ];

  foreach ($keys as $key) {
    \Drupal::configFactory()->getEditable($key)->delete();
  }
}
