<?php

/**
 * @file
 * Contains rightside_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rightside_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rightside_block module.
    case 'help.page.rightside_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Rightside Block') . '</p>';
      return $output;

    default:
  }
}
