<?php

/**
 * @file
 * Contains webcomposer_mobile_menu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webcomposer_mobile_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_mobile_menu module.
    case 'help.page.webcomposer_mobile_menu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides configuration for mobile menu.') . '</p>';
      return $output;

    default:
  }
}
