<?php

/**
 * @file
 * Contains mobile_product_menu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_product_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mobile_product_menu module.
    case 'help.page.mobile_product_menu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Left Menu Entity for products') . '</p>';
      return $output;

    default:
  }
}
