<?php

/**
 * @file
 * Contains jamboree_canonical.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jamboree_canonical_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jamboree_canonical module.
    case 'help.page.jamboree_canonical':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Jamboree Canonical') . '</p>';
      return $output;

    default:
  }
}
