<?php

/**
 * @file
 * Contains news_and_updates.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function news_and_updates_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the news_and_updates module.
    case 'help.page.news_and_updates':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('News and Updates') . '</p>';
      return $output;

    default:
  }
}
