<?php

/**
 * @file
 * Contains jamboree_weekly_winner.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jamboree_weekly_winner_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jamboree_weekly_winner module.
    case 'help.page.jamboree_weekly_winner':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Jamboree Weekly Winner') . '</p>';
      return $output;

    default:
  }
}
