<?php

/**
 * @file
 * Contains lucky_baby_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_help().
 */
function lucky_baby_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lucky_baby_config module.
    case 'help.page.lucky_baby_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('777baby casino configuration') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_alter().
 */
function lucky_baby_config_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // specifically for webcomposer form manager list alter expanding row delta range
  if ($form['#form_id'] == 'webcomposer_form_manager.manage_form') {
    foreach ($form['table'] as $key => $value) {
      if (empty(strpos($key, '#')) && strpos($key, '#') !== 0) {
        $form['table'][$key]['weight']['#delta'] = 50;
      }
    }
  }
}