<?php

/**
 * @file
 * Contains zipang_dropdown_menu.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zipang_dropdown_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zipang_dropdown_menu module.
    case 'help.page.zipang_dropdown_menu':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Main Menu for Zipang Casino site') . '</p>';
      return $output;

    default:
  }
}
