<?php

/**
 * @file
 * Contains nextbet_urls.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nextbet_urls_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nextbet_urls module.
    case 'help.page.nextbet_urls':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Nextbet Urls specific configurations') . '</p>';
      return $output;

    default:
  }
}
