<?php

/**
 * @file
 * Contains keno_lobby_tile.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function keno_lobby_tile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the keno_lobby_tile module.
    case 'help.page.keno_lobby_tile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles keno lobby tile configurations') . '</p>';
      return $output;

    default:
  }
}
