<?php

/**
 * @file
 * Contains keno_lobby_tile.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function keno_lobby_tile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main modules help for the keno_lobby_tile module.
    case 'help.page.keno_lobby_tile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles keno lobby tile configurations') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_alter().
 *
 * Hide the Both select option of Log-in State from Basic Page Template
 */
function keno_lobby_tile_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_page_form' || $form_id == 'node_page_edit_form'){
    unset($form['field_log_in_state']['widget']['#options'][2]);
  }
}
