<?php

/**
 * @file
 */

/**
 * Implements hook_webcomposer_form_validation_alter().
 *
 * Additional Validation
 */
function zedbet_forms_webcomposer_form_validation_alter(&$validations) {
  $validations['username_availability'] = [
    'title' => 'Username Availability',
    'description' => 'Validate username if already exist',
    'error' => 'Username not available',
  ];
  $validations['email_availability'] = [
    'title' => 'Email Availability',
    'description' => 'Validate user email if already exist',
    'error' => 'Email not available',
  ];
  $validations['invalid_words'] = [
    'title' => 'Invalid Words',
    'description' => 'Validation to disallow specific words in the field',
    'error' => 'Invalid/not allowed characters',
    'parameters' => [
      'invalid_words_list' => [
        '#title' => 'Invalid Words List',
        '#description' => 'List of words to disallow',
        '#type' => 'textarea',
      ],
    ],
  ];
  $validations['valid_languages'] = [
    'title' => 'Valid Languages',
    'description' => 'Validation to allow or disallow specific languages based on regex value',
    'error' => "This field only accepts specific characters.",
    'parameters' => [
      'regex_value' => [
        '#title' => 'Regex String',
        '#description' => 'Regex value that will be tested on the front end. ' .
          '(Only configure this if you know how to code a regex)',
        '#type' => 'textarea',
      ],
    ],
  ];
  $validations['valid_date'] = [
    'title' => 'Valid Date',
    'description' => 'Validation to check if the inputted date is correct based on format' .
      '(must have a Birthdate format on field settings)',
    'error' => 'Date is invalid',
  ];
  // password validation
  $validations['not_match_username'] = [
    'title' => 'Not Match Username',
    'description' => 'Validation to disallow current username as password',
    'error' => 'Password should not equal to username',
  ];

  $validations['verify_password'] = [
    'title' => 'Verify Password',
    'description' => 'Validation to confirm new password.',
    'error' => 'Password not match.',
  ];

  $validations['allowed_date'] = [
    'title' => 'Allowed Date',
    'description' => 'Validation to confirm allowed date.',
    'error' => 'Date is not allowed.',
  ];

  $validations['number_required'] = [
    'title' => 'Number value required',
    'description' => 'If this validation is enabled we need to pass one number value in field.',
    'error' => 'Field requires at least one number to be passed.',
  ];

  $validations['capital_letter_required'] = [
    'title' => 'Capital letter value required',
    'description' => 'If this validation is enabled we need to pass one capital letter in input field.',
    'error' => 'Field requires at least one capital letter to be passed.',
  ];

  $validations['lower_letter_required'] = [
    'title' => 'Lower letter value required',
    'description' => 'If this validation is enabled we need to pass one lower letter in input field.',
    'error' => 'Field requires at least one lower letter to be passed.',
  ];

  $validations['not_match_current_password'] = [
    'title' => 'Must Not Match Current Password',
    'description' => 'This validation is checking if passwords are not same with current password.',
    'error' => 'Should not be same as current password.',
  ];

  $validations['new_confirm_password_match'] = [
    'title' => 'New And Confirm Password Match',
    'description' => 'This validation is checking if new and current passwords are same.',
    'error' => 'Passwords should be same.',
  ];
}
