<?php

/**
 * @file
 * Contains arcade_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function arcade_config_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the arcade_config module.
    case 'help.page.arcade_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module for nextbet specific updates') . '</p>';
      return $output;

    default:
  }
}

function arcade_config_form_alter(&$form, $form_state, $form_id)
{
    $submitAction = false;
    switch ($form_id) {
      case 'taxonomy_term_arcade_game_categories_form':
      case 'taxonomy_term_arcade_game_categories_delete_form':
        $submitAction = '_arcade_config_game_category_form_submit';
        break;
      case 'node_arcade_game_delete_form':
      case 'node_arcade_game_form':
        $submitAction = '_arcade_config_game_thumbnail_form_submit';
        break;
    }

    if ($submitAction !== false) {
        foreach (array_keys($form['actions']) as $action) {
            if ($action != 'preview' && isset($form['actions'][$action]['#type']) &&
              $form['actions'][$action]['#type'] === 'submit') {
                $form['actions'][$action]['#submit'][] = $submitAction;
            }
        }
    }
}

// redirection when editing & deleting category
function _arcade_config_game_category_form_submit($form, &$form_state)
{
    $form_state->setRedirect('arcade_config.game.categories');
}

// redirection when editing & deleting thumbnails
function _arcade_config_game_thumbnail_form_submit($form, &$form_state)
{
    $form_state->setRedirect('arcade_config.game.thumbnails');
}
