<?php

/**
 * @file
 * Contains jamboree_jackpot.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jamboree_jackpot_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jamboree_jackpot module.
    case 'help.page.jamboree_jackpot':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Jamboree Jackpot') . '</p>';
      return $output;

    default:
  }
}
