<?php

function casino_editor_editor_js_settings_alter(&$settings) {
    foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
        if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
            $settings['editor']['formats'][$text_format_id]['editorSettings']['extraAllowedContent'] = 'span(*)[data-font-color,data-font-size];a(*)[target,href]';
            $settings['editor']['formats'][$text_format_id]['editorSettings']['startupOutlineBlocks'] = true;
            // $settings['editor']['formats'][$text_format_id]['editorSettings']['startupMode'] = 'source';
            $settings['editor']['formats'][$text_format_id]['editorSettings']['removePlugins'] = 'link';
        }        
    }
}