<?php

/**
 * @file
 * Contains casino_games.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function casino_games_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the casino_games module.
    case 'help.page.casino_games':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
