<?php

/**
 * @file
 * Contains mobile_sponsor_list_v2.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\TranslatableInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_sponsor_list_v2_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the mobile_sponsor_list_v2 module.
    case 'help.page.mobile_sponsor_list_v2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mobile Sponsor List version 2.0 configuration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Form alter for webcomposer_ section.
 */
function mobile_sponsor_list_v2_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  $forms = [
    'mobile_sponsor_list_v2_add_form',
    'mobile_sponsor_list_v2_edit_form',
  ];
  if (in_array($form_id, $forms)) {
    $form['#validate'][] = 'mobile_sponsor_list_v2_validate';
  }
}
