<?php

/**
 * @file
 * Contains zipang_seo_configuration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zipang_seo_configuration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zipang_seo_configuration module.
    case 'help.page.zipang_seo_configuration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Zipang metatag entity') . '</p>';
      return $output;

    default:
  }
}
