<?php

/**
 * @file
 * Contains entrypage_partners.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entrypage_partners_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entrypage_partners module.
    case 'help.page.entrypage_partners':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module shows entrypage partners.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function entrypage_partners_theme() {
  return [
    'entrypage_partners' => [
      'template' => 'entrypage_partners',
      'render element' => 'children',
    ],
  ];
}
