<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\TranslatableInterface;

/**
 * Form alter for webcomposer_slider_v2 section.
 */
function webcomposer_slider_v2_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $forms = [
    'webcomposer_slider_v2_entity_add_form',
    'webcomposer_slider_v2_entity_edit_form',
  ];
  if (in_array($form_id, $forms)) {
    $form['#validate'][] = 'webcomposer_slider_v2_validate';
  }
}

/**
 * Form validation for webcomposer_slider_v2 scheduler.
 */
function webcomposer_slider_v2_validate(&$form, FormStateInterface $form_state) {
  $publish = $form_state->getValue('field_publish_date');
  $unpublish = $form_state->getValue('field_unpublish_date');
  $loginState = $form_state->getValue('field_log_in_state');
  $bannerImage = $form_state->getValue('field_banner_image');
  $bannerImagePost = $form_state->getValue('field_post_banner_image');

  $publishDate = isset($publish[0]['value']) ? $publish[0]['value']->format('U') : NULL;
  $unpublishDate = isset($unpublish[0]['value']) ? $unpublish[0]['value']->format('U') : NULL;

  if ($unpublishDate && $unpublishDate < $publishDate) {
    $form_state->setErrorByName('field_unpublish_date', t('Unpublish date should be greater than the publish date.'));
  }
  // Validation for pre bammer image.
  if ($loginState[0]['value'] == 0 && $bannerImage[0]['fids'] == NULL) {
    $form_state->setErrorByName('$bannerImage', t('Pre Banner Image field is required.'));
  }
  // Validation for pre bammer image.
  if ($loginState[1]['value'] == 1 && $bannerImagePost[0]['fids'] == NULL) {
    $form_state->setErrorByName('$bannerImagePost', t('Post Banner Image field is required.'));
  }
}
