<?php

/**
 * @file
 * Contains matterhorn_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function matterhorn_blocks_help($route_name, RouteMatchInterface $route_match) 
{
    switch ($route_name) {
        // Main module help for the matterhorn_blocks module.
        case 'help.page.matterhorn_blocks':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Provides an API for defining custom block entries') . '</p>';

            return $output;
    }
}
