<?php

/**
 * @file
 * Contains webcomposer_dashboard.module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function webcomposer_dashboard_toolbar() {
  $items['webcomposer'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Webcomposer'),
      '#url' => Url::fromRoute('webcomposer.admin'),
      '#attributes' => [
        'title' => t('Webcomposer'),
        'class' => ['toolbar-icon', 'toolbar-icon-webcomposer'],
      ],
    ],
    'tray' => [
      '#heading' => t('Webcomposer menu'),
      'webcomposer' => [
        '#theme' => 'item_list',
        '#items' => [],
      ],
    ],
    '#attached' => [
      'library' => [
        'webcomposer_dashboard/webcomposer.toolbar',
      ],
    ],
    '#weight' => 900,
  ];

  return $items;
}
