<?php

/**
 * @file
 * Contains webcomposer_dashboard.module.
 */

use Drupal\Core\Url;
use DrupalProject\custom\EnvironmentResolver;

/**
 * Implements hook_toolbar().
 */
function webcomposer_dashboard_toolbar() {
  $items['webcomposer'] = [
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#title' => t('Webcomposer'),
      '#url' => Url::fromRoute('webcomposer.admin'),
      '#attributes' => [
        'title' => t('Webcomposer'),
        'class' => ['toolbar-icon', 'toolbar-icon-webcomposer'],
      ],
    ],
    '#attached' => [
      'library' => [
        'webcomposer_dashboard/webcomposer.toolbar',
      ],
    ],
    '#weight' => 900,
  ];

  return $items;
}

function webcomposer_dashboard_page_top(&$page) {
  $env = EnvironmentResolver::getEnvironment();

  if ($env === 'PRD') {
    $message = "You are editing <strong>PRODUCTION</strong> environment";

    $page['webcomposer_warning'] = [
      '#markup' => "
        <div class='webcomposer-status-message'>
          $message
        </div>
      ",
    ];
  }
}
