<?php

/**
 * @file
 * Contains casino_games_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function casino_games_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the casino_games_search module.
    case 'help.page.casino_games_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Casino Games Search Recommendation Module') . '</p>';
      return $output;

    default:
  }
}