<?php

/**
 * @file
 * Contains mobile_slots.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_slots_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mobile_slots module.
    case 'help.page.mobile_slots':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Slots configuration module') . '</p>';
      return $output;

    default:
  }
}
