<?php

/**
 * @file
 * Contains arcade.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_arcade_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the arcade module.
    case 'help.page.mobile_arcade':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Arcade configuration module') . '</p>';
      return $output;

    default:
  }
}
