<?php

/**
 * @file
 * Contains soda_casino.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function soda_casino_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the soda_casino module.
    case 'help.page.soda_casino':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Soda Casino configuration module') . '</p>';
      return $output;

    default:
  }
}
