<?php

/**
 * @file
 * The ldaphelp module is a module to help admins debug ldap_integration modules.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_form_ldap_servers_settings_alter().
 *
 * Alter LDAP settings form to add watchdog details.
 */
function ldap_help_form_ldap_servers_settings_alter(&$form, FormStateInterface $form_state) {
  $form['watchdog_detail'] = array('#type' => 'fieldset', '#title' => t('Debugging'));
  $form['watchdog_detail']['watchdog_detail'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enabled Detailed LDAP Watchdog logging. This is generally for
       debugging and reporting issues with the ldap modules and should not be left
       on.'),
    '#default_value' => \Drupal::config('ldap_help.settings')->get('watchdog_detail'),
  );
  $form['#submit'][] = 'ldap_help_watchdog_detail_submit';
}

/**
 * Implements hook_form_submit().
 *
 * Alter LDAP settings form submission handler to add watchdog details.
 */
function ldap_help_watchdog_detail_submit(array &$form, FormStateInterface $form_state) {
  if ($form_state->isSubmitted()) {
    $config = \Drupal::configFactory()->getEditable('ldap_help.settings');
    $watchdog_detail = $form_state->getValue('watchdog_detail');
    if ($watchdog_detail != $config->get('watchdog_detail')) {
      $config->set('watchdog_detail', $watchdog_detail);
    }
    $config->save();
  }
}

/**
 * Implements hook_help().
 */
function ldap_help_help($route_name, RouteMatchInterface $route_match) {

  $help = '<h3>' . t('LDAP Help Module') . '</h3><p>' .
  t('This module assists Drupal admins in configuring, debugging, sharing, and submitting
  support and bug request related to LDAP modules.') . '<strong><em> ' .
  t('LDAP Help Module should be disabled unless you are debugging or configuring
    LDAP problems.') . ' </em></strong>' .
  t('It adds no functionality to the LDAP modules.') . '</p>';

  switch ($route_name) {
    case 'admin/config/people/ldap/help':
      return '<p>' . $help . '</p>';

    case 'admin/help#ldap_help':
      return '<p>' . $help . '</p>';
  }

}
