<?php

/**
 * @file
 * Contains zedbet_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function zedbet_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zedbet_config module.
    case 'help.page.zedbet_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module for zedbet specific updates') . '</p>';
      return $output;

    default:
  }
}

function zedbet_config_form_alter(&$form, $form_state, $form_id) {
  if (in_array($form_id, ['node_mobile_form', 'node_mobile_edit_form'])){
    $form['field_mobile_tab_title']['widget'][0]['value']['#label_attributes']['class'][] = "form-required";
    $form['field_mobile_banner_image']['widget'][0]['#label_attributes']['class'][] = "form-required";
    $form['field_android_tab_title']['widget'][0]['value']['#label_attributes']['class'][] = "form-required";
    $form['field_android_banner_image']['widget'][0]['#label_attributes']['class'][] = "form-required";
    $form['#validate'][] = 'zedbet_config_validate';
  }
}

function zedbet_config_validate(&$form, $form_state) {
  $ids = [];
  foreach ($form_state->getValue('field_menu_tab') as $menu) {
    $ids = array_merge($ids, array_values($menu));
  }

  // Mobile tab required fields
  if (in_array('0', $ids)) {
    if (empty($form_state->getValue('field_mobile_tab_title')[0]['value'])) {
      $form_state->setError($form['field_mobile_tab_title'], t('Mobile tab title field is required.'));
    }

    if (empty($form_state->getValue('field_mobile_banner_image')[0]['fids'])) {
      $form_state->setError($form['field_mobile_banner_image'], t('Mobile banner image field is required.'));
    }
  }

  // Android tab required fields
  if (in_array('1', $ids)) {
    if (empty($form_state->getValue('field_android_tab_title')[0]['value'])) {
      $form_state->setError($form['field_android_tab_title'], t('Android tab title field is required.'));
    }

    if (empty($form_state->getValue('field_android_banner_image')[0]['fids'])) {
      $form_state->setError($form['field_android_banner_image'], t('Android banner image field is required.'));
    }
  }
}
