<?php

/**
 * @file
 * Contains webcomposer_floating_banners.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webcomposer_floating_banners_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_floating_banners module.
    case 'help.page.webcomposer_floating_banners':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Floating Banners functionality for Web Composer') . '</p>';
      return $output;

    default:
  }
}
