<?php

/**
 * @file
 * Contains webcomposer_als_whitelisting.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webcomposer_als_whitelisting_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_als_whitelisting module.
    case 'help.page.webcomposer_als_whitelisting':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module take care of ALS whitelisting.') . '</p>';
      return $output;

    default:
  }
}
