<?php

/**
 * @file
 * Contains payment_method_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function payment_method_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the payment_method_list module.
    case 'help.page.payment_method_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Description') . '</p>';
      return $output;

    default:
  }
}
