<?php

/**
 * @file
 * Contains ghana_quick_links.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ghana_quick_links_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ghana_quick_links module.
    case 'help.page.ghana_quick_links':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ghana Quick Links Module') . '</p>';
      return $output;

    default:
  }
}
