<?php

/**
 * @file
 * Contains mobile_owsports.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_owsports_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mobile_owsports module.
    case 'help.page.mobile_owsports':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OWSports integration configurations') . '</p>';
      return $output;

    default:
  }
}
