<?php

/**
 * @file
 * Contains webcomposer_optin_report.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function casino_optin_provision_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_optin_report module.
    case 'help.page.webcomposer_optin_report':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides Opt-in Reporting Tool') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_cron()
 */
function casino_optin_provision_cron() {
  $formatedDate = date("Y-m-d", time());

  // Note: No configuration for 30 days purging
  $thirtyDays = strtotime("$formatedDate -30 days");

  $isDeleted = \Drupal::database()->delete("casino_optin_report")
                ->condition("application_date", $thirtyDays, "<")
                ->execute();

  if ($isDeleted) {
    \Drupal::logger('my_module')->notice("All Data older than $thirtyDays are deleted.");
  } else {
    \Drupal::logger('my_module')->error("Error deleting data");
  }
}
