<?php

/**
 * @file
 * Contains webcomposer_optin_report.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function casino_optin_provision_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_optin_report module.
    case 'help.page.webcomposer_optin_report':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides Opt-in Reporting Tool') . '</p>';
      return $output;

    default:
  }
}
