<?php

/**
 * @file
 * Contains entrypage_promotions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Database\Database;

/**
 * Implements hook_help().
 */
function entrypage_promotions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entrypage_promotions module.
    case 'help.page.entrypage_promotions':
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('This module takes of entrypage specific promotions features.') . '</p>';
    return $output;

    default:
  }
}

