<?php

/**
 * @file
 * Contains entrypage_promotions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Database\Database;

/**
 * Alter form options by id.
 *
 * @param array $options
 *   An associative array of options.
 * @param array $element
 *   The form element that the options is for.
 * @param string $options_id
 *   The form options id. Set to NULL if the options are custom.
 */
function entrypage_promotions_webform_options_alter(array &$options, array &$element, $options_id = NULL) {
    die();
    kint(func_get_args());
}

/**
 * Perform alterations on webform admin third party settings form.
 */
function entrypage_promotions_webform_admin_third_party_settings_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
    die('lols');
}
