<?php

/**
 * @file
 * Contains zedbet_front_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zedbet_front_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zedbet_front_blocks module.
    case 'help.page.zedbet_front_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for Zedbet home blocks.') . '</p>';
      return $output;

    default:
  }
}
