<?php

/**
 * @file
 * Contains jamboree_payment_method.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jamboree_payment_method_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jamboree_payment_method module.
    case 'help.page.jamboree_payment_method':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Jamboree Payment Method Module') . '</p>';
      return $output;

    default:
  }
}
