<?php

/**
 * @file
 * Contains webcomposer_audit.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 *
 */
function webcomposer_audit_entity_update(EntityInterface $entity) {
  try {
    \Drupal::service('webcomposer_audit.database_storage')->update($entity);
  } catch (\Exception $e) {
    // do nothing
  }
}

/**
 *
 */
function webcomposer_audit_entity_insert(EntityInterface $entity) {
  try {
    \Drupal::service('webcomposer_audit.database_storage')->insert($entity);
  } catch (\Exception $e) {
    // do nothing
  }
}

/**
 *
 */
function webcomposer_audit_entity_delete(EntityInterface $entity) {
  try {
    \Drupal::service('webcomposer_audit.database_storage')->delete($entity);
  } catch (\Exception $e) {
    // do nothing
  }
}
