<?php

/**
 * @file
 * Contains webcomposer_audit.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 *
 */
function webcomposer_audit_entity_presave(EntityInterface $entity) {
  \Drupal::service('webcomposer_audit.database_storage')->presave($entity);
}

/**
 *
 */
function webcomposer_audit_entity_update(EntityInterface $entity) {
  \Drupal::service('webcomposer_audit.database_storage')->add($entity);
}
