<?php

/**
 * @file
 * Contains webcomposer_single_signon.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webcomposer_single_signon_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_single_signon module.
    case 'help.page.webcomposer_single_signon':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides configuration for single signon') . '</p>';
      return $output;

    default:
  }
}
