<?php

/**
 * @file
 * Contains lucky_baby_jackpot.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lucky_baby_jackpot_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lucky_baby_jackpot module.
    case 'help.page.lucky_baby_jackpot':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Jackpot') . '</p>';
      return $output;

    default:
  }
}
