<?php

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Render\Markup;

/**
 * Implements hook_module_implements_alter()
 */
function casino_config_module_implements_alter(&$implementations, $hook)
{
    if ($hook == 'form_alter')
    {
      // Move the casino editor as last module to override
      // the form alter from the scheduler.
      $group = $implementations['casino_config'];
      unset($implementations['casino_config']);
      $implementations['casino_config'] = $group;
    }
}

function casino_config_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // remove access to content translation field
  $form['content_translation']['#access'] = false;
  // hide the description on publish/unpublish from scheduler module
  unset($form['unpublish_on']['widget'][0]['value']['#description']);
  unset($form['publish_on']['widget'][0]['value']['#description']);
}


/**
 * Implements hook_cron()
 */
function casino_config_cron() {
  /**
   * Casino Provision
   * Purge table after 30 days
   * Start
   */
  try {
    $formatedDate = date("Y-m-d", time());

    // Note: No configuration for 30 days purging
    $thirtyDays = strtotime("$formatedDate -30 days");

    \Drupal::database()->delete("casino_provision_report")
                  ->condition("application_date", $thirtyDays, "<")
                  ->execute();

    $dateFormat = date("Y-m-d", $thirtyDays);
    \Drupal::logger('casino_provision')->notice("All data older than $dateFormat are deleted.");

  } catch (\Exception $e) {
    \Drupal::logger('casino_provision')->error($e);
  }
  // End Casino Provision

}

