<?php

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Render\Markup;

/**
 * Implements hook_module_implements_alter()
 *
 * @var array $implementations
 *    An array keyed by the module's name.
 *
 * @var string $hook
 *  The name of the module hook being implemented.
 */
function casino_config_module_implements_alter(&$implementations, $hook)
{
  if ($hook == 'form_alter')
  {
    // Move the casino editor as last module to override
    // the form alter from the scheduler.
    $group = $implementations['casino_config'];
    unset($implementations['casino_config']);
    $implementations['casino_config'] = $group;
  }
}


/**
 * Implements hook_module_implements_alter()
 *
 * @var array $form
 *    Nested array of form elements that comprise the form.
 *
 * @var \Drupal\Core\Form\FormStateInterface $form_state
 *    The current state of the form.
 *
 * @var string $form_id
 *    String representing the name of the form itself.
 *
 */
function casino_config_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // remove access to content translation field
  $form['content_translation']['#access'] = false;
  // hide the description on publish/unpublish from scheduler module
  unset($form['unpublish_on']['widget'][0]['value']['#description']);
  unset($form['publish_on']['widget'][0]['value']['#description']);
}


/**
 * Implements hook_cron()
 */
function casino_config_cron() {
  /**
   * Casino Provision
   * Purge table after 30 days
   * Start
   */
  try {
    $formatedDate = date("Y-m-d", time());

    // Note: No configuration for 30 days purging
    $thirtyDays = strtotime("$formatedDate -30 days");

    \Drupal::database()->delete("casino_provision_report")
                  ->condition("application_date", $thirtyDays, "<")
                  ->execute();

    $dateFormat = date("Y-m-d", $thirtyDays);
    \Drupal::logger('casino_provision')->notice("All data older than $dateFormat are deleted.");

  } catch (\Exception $e) {
    \Drupal::logger('casino_provision')->error($e);
  }
  // End Casino Provision

}

