<?php

function webcomposer_editor_editor_js_settings_alter(&$settings) {
    $languages = [
        'zh-hans' => 'sc',
        'zh-hant' => 'ch',
    ];

    $site = basename(str_replace('/files', '', \Drupal::service('file_system')->realpath("public://")));

    foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
        if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
            $settings['editor']['formats'][$text_format_id]['editorSettings']['extraAllowedContent'] = 'span(*)[data-font-color,data-font-size];a(*)[target,href]';
            $settings['editor']['formats'][$text_format_id]['editorSettings']['startupOutlineBlocks'] = true;
            // $settings['editor']['formats'][$text_format_id]['editorSettings']['startupMode'] = 'source';
            $settings['editor']['formats'][$text_format_id]['editorSettings']['removePlugins'] = 'drupallink';

            $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
            $langCode = $languages[$langId] ?? 'sc';

            $settings['editor']['formats'][$text_format_id]['editorSettings']['language'] = $langCode;
            $settings['editor']['formats'][$text_format_id]['editorSettings']['site'] = $site;
        }
    }
}
