<?php

/**
 * @file
 * Contains zipang_faq.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zipang_faq_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zipang_faq module.
    case 'help.page.zipang_faq':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Zipang FAQ') . '</p>';
      return $output;

    default:
  }
}
