<?php
kint_require();
/**
 * Implements hook_form_alter().
 */
function webcomposer_permission_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  $formObject = $form_state->getFormObject();
  if ($formObject instanceof \Drupal\Core\Entity\EntityFormInterface) {
    $entity = $formObject->getEntity();

    // Make sure it's a node.
    if ($entity instanceof \Drupal\node\NodeInterface) {
        // hide author fields in nodes
        if (isset($form['uid'])) {
            $form['uid']['#access'] = FALSE;
        }
        if (isset($form['created'])) {
            $form['created']['#access'] = FALSE;
        }
    }
    // Make sure it's a content entity.
    if ($entity instanceof \Drupal\Core\Entity\ContentEntityInterface) {

        // hide author field in content entities
        if (isset($form['user_id'])) {
            $form['user_id']['#access'] = FALSE;
        }
        // hide author field in content translation entities
        if (isset($form['content_translation']['uid'])) {
            $form['content_translation']['uid']['#access'] = FALSE;
        }
        if (isset($form['content_translation']['created'])) {
            $form['content_translation']['created']['#access'] = FALSE;
        }
    }
  }
}