<?php

/**
 * @file
 * Contains zipang_desktop_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zipang_desktop_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zipang_desktop_blocks module.
    case 'help.page.zipang_desktop_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Zipang Desktop Blocks') . '</p>';
      return $output;

    default:
  }
}
