<?php

/**
 * @file
 * Contains zipang_registration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zipang_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jamboree_registration module.
    case 'help.page.zipang_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Casino Zipang Registration') . '</p>';
      return $output;

    default:
  }
}
