<?php

/**
 * @file
 * Contains lucky_baby_desktop_games.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lucky_baby_desktop_games_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lucky_baby_desktop_games module.
    case 'help.page.lucky_baby_desktop_games':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for desktop games') . '</p>';
      return $output;

    default:
  }
}
