<?php

/**
 * @file
 * Contains webcomposer_audit_export.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webcomposer_audit_export_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_audit_export module.
    case 'help.page.webcomposer_audit_export':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module take care of audit logs export.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function webcomposer_audit_export_theme() {
  return [
    'webcomposer_audit_export' => [
      'template' => 'webcomposer_audit_export',
      'render element' => 'children',
    ],
  ];
}
