<?php

/**
 * @file
 * Support module for Replicate module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\TranslatableInterface;
use Drupal\Core\Entity\ContentEntityForm;

 /**
 * Form alter for webcomposer_floating_banners section.
 */
function webcomposer_replicate_utility_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    $forms = [
      'webcomposer_slider_v2_entity_replicate_form',
      'left_floating_banner_entity_replicate_form',
    ];
    if (in_array($form_id, $forms)) {
      $form_object = $form_state->getFormObject();
      if ($form_object instanceof ContentEntityForm) {
        $entity = $form_object->getEntity();
        if ($entity instanceof TranslatableInterface) {
          foreach ($entity->getTranslationLanguages() as $translation_language) {  
            $langcode = $translation_language->getId();
            /** @var \Drupal\Core\Entity\TranslatableInterface $translation */
            $translation = $entity->getTranslation($langcode);
            $field_name = 'new_label_' . $langcode;
            $default_value = $form[$field_name]['#default_value'];
            $title = $translation->get('field_title')->getString();
            if (!empty($title)) {
              $form[$field_name]['#default_value'] = $title . ' (Copy)';
            }
          }
        }
        else {
          $title = $entity->get('field_title')->getString();
          $form['new_label']['#default_value'] = $title . ' (Copy)';
        }
      }
   }
}