<?php

/**
 * @file
 * Contains webcomposer_config.module.
 */

/**
 * Perform alterations on webform third party settings form.
 */
function webcomposer_config_webform_third_party_settings_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $settings = $form_state->getFormObject()->getEntity();

  // put the form side by side
  $form['general_settings']['#weight'] = -10;
  $form['third_party_settings']['#weight'] = -5;

  $form['third_party_settings']['webform_layout'] = [
    '#type' => 'details',
    '#title' => t('Layout Settings'),
  ];

  $form['third_party_settings']['webform_layout']['background_image'] = array(
    '#type' => 'webform_image_file',
    '#title' => t('Form Background Image'),
    '#description' => t('The background image of the form'),
    '#default_value' => $settings->getThirdPartySetting('webform_layout', 'background_image'),
  );

  $form['third_party_settings']['webform_layout']['font_color'] = array(
    '#type' => 'color',
    '#title' => t('Label Font Color'),
    '#description' => t('The color of the label'),
    '#default_value' => $settings->getThirdPartySetting('webform_layout', 'font_color'),
  );

  $form['third_party_settings']['webform_layout']['error_color'] = array(
    '#type' => 'color',
    '#title' => t('Error Font Color'),
    '#description' => t('The color of the error label'),
    '#default_value' => $settings->getThirdPartySetting('webform_layout', 'error_color'),
  );

  $form['#validate'][] = '_webcomposer_config_webform_form_validate';
}

/**
 * Validate function
 */
function _webcomposer_config_webform_form_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $settings = $form_state->getFormObject()->getEntity();

  // fix for image uploads breaking due to unknown reasons that the scheduled date
  // gets validated on image upload AJAX calls
  $date = $settings->get('open')['date'];
  if (!$date) {
    $settings->set('open', FALSE);
  }

  $date = $settings->get('close')['date'];
  if (!$date) {
    $settings->set('close', FALSE);
  }

  // remove the background image upload on empty background
  $third_party_settings = $form_state->getValue('third_party_settings');
  if (empty($third_party_settings['webform_layout']['background_image'])) {
    unset($third_party_settings['webform_layout']['background_image']);
  }

  $form_state->setValue('third_party_settings', $third_party_settings);
}
