<?php
/**
 * @file
 * Containstournament_api.module. */use Drupal\Core\Routing\RouteMatchInterface;/**
 * Implements hook_help().
 */
function tournament_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for thetournament_api module.
    case 'help.page.tournament_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tournament Api') . '</p>';
      return $output;

    default:
  }
}