<?php

/**
 * @file
 * Contains jamboree_arcade.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jamboree_arcade_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jamboree_arcade module.
    case 'help.page.jamboree_arcade':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Jamboree Arcade Games') . '</p>';
      return $output;

    default:
  }
}
