<?php

/**
 * @file
 * Contains jamboree_withdraw_method.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jamboree_withdraw_method_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jamboree_withdraw_method module.
    case 'help.page.jamboree_withdraw_method':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for withdraw method') . '</p>';
      return $output;

    default:
  }
}
