<?php


/**
 * @file
 * Contains webcomposer_cache.module.
 */

/**
 * Implements hook_cache_flush().
 */
function webcomposer_cache_cache_flush() {
  try {
    $enable = \Drupal::config('webcomposer_cache.settings')->get('enable');

    if ($enable) {
      \Drupal::service('webcomposer_cache.signature_manager')->renewSignature();
    }
  } catch (Exception $e) {
    // do nothing
  }
}

/**
 * Implements hook_scheduler_nid_list_alter().
 * @param  array  &$nids  [list of nids scheduled for update]
 * @return [array]         [list of nids]
 */
function webcomposer_cache_scheduler_nid_list_alter(array &$nids, $action) {
  // Regenerate cache signature if we have nids in queue on scheduler.
  if ($nids) {
    try {
      \Drupal::service('webcomposer_cache.signature_manager')->renewSignature();
    } catch (Exception $e) {
      // do nothing
    }
  }

  return $nids;

}
