<?php

use Drupal\Core\Url;

/**
 * @file
 * Contains webcomposer_cache.module.
 */

/**
 * Implements hook_cache_flush().
 */
function webcomposer_cache_cache_flush() {
  try {
    $enable = \Drupal::config('webcomposer_cache.settings')->get('enable');

    if ($enable) {
      \Drupal::service('webcomposer_cache.signature_manager')->renewSignature();
    }
  } catch (Exception $e) {
    // do nothing
  }
}

/**
 * Implements hook_scheduler_nid_list_alter().
 *
 * @param array &$nids List of nids scheduled for update
 *
 * @return array List of nids
 */
function webcomposer_cache_scheduler_nid_list_alter(array &$nids, $action) {
  // Regenerate cache signature if we have nids in queue on scheduler.
  if ($nids) {
    try {
      \Drupal::service('webcomposer_cache.signature_manager')->renewSignature();
    } catch (Exception $e) {
      // do nothing
    }
  }

  return $nids;
}

function webcomposer_cache_toolbar_alter(&$items) {
  // Move the User tab to the right.
  $items['webcomposer']['tray']['wbc_menu']['#items']['configuration'] = [
    '#type' => 'link',
    '#title' => t('Configure'),
    '#url' => Url::fromRoute('webcomposer_cache.new_signature'),
  ];
}
