<?php

/**
 * @file
 * Providesa sportsbook widget api entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function sportsbook_widget_api_theme()
{
  return [
    'sportsbook_widget_api' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables forsportsbook widget api templates.
 *
 * Default template:sportsbook-widget-api.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing thesportsbook widget api information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sportsbook_widget_api(array &$variables)
{
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
