<?php

/**
 * @file
 */

/**
 * Implements hook_webcomposer_form_validation_alter().
 */
function my_account_form_webcomposer_form_validation_alter(&$validations) {
  $validations['same'] = [
    'title' => 'Username Availability',
    'description' => 'Validate username if already exist',
    'error' => 'Username not available',
  ];

  $validations['invalid_words'] = [
    'title' => 'Invalid Words',
    'description' => 'Validation to disallow specific words in the field',
    'error' => 'Invalid/not allowed characters',
    'parameters' => [
      'invalid_words_list' => [
        '#title' => 'Invalid Words List',
        '#description' => 'List of words to disallow',
        '#type' => 'textarea',
      ],
    ],
  ];

  // password validation
  $validations['not_match_username'] = [
    'title' => 'Not Match Username',
    'description' => 'Validation to disallow current username as password.
    <br><br> <strong>Note:</strong> This rule should only be enabled on forms <u>where the username is available </u> eg:( New User Registration, Account Update on post-login ).',
    'error' => 'Password should not equal to username',
  ];

  $validations['verify_password'] = [
    'title' => 'Verify Password',
    'description' => 'Validation to confirm new password.',
    'error' => 'Password not match.',
  ];

  $validations['allowed_date'] = [
    'title' => 'Allowed Date',
    'description' => 'Validation to confirm allowed date.',
    'error' => 'Date is not allowed.',
  ];

  $validations['number_required'] = [
    'title' => 'Number value required',
    'description' => 'If this validation is enabled we need to pass one number value in field.',
    'error' => 'Field requires at least one number to be passed.',
  ];

  $validations['capital_letter_required'] = [
    'title' => 'Capital letter value required',
    'description' => 'If this validation is enabled we need to pass one capital letter in input field.',
    'error' => 'Field requires at least one capital letter to be passed.',
  ];

  $validations['lower_letter_required'] = [
    'title' => 'Lower letter value required',
    'description' => 'If this validation is enabled we need to pass one lower letter in input field.',
    'error' => 'Field requires at least one lower letter to be passed.',
  ];
  $validations['new_password_different_from_current'] = [
    'title' => 'New Pass Diff. From Current',
    'description' => 'If this validation is enabled we need the new password to be different from the one entered in the "Current Password" field.
      <br><br> <strong>Note:</strong> This rule should only be enabled in pages <u>where there is a "current password" input field</u>.',
    'error' => 'Must not be the same as the current password.',
  ];
}
