<?php

use Drupal\Component\Utility\Html;

/**
 * @file
 * Contains contact_us_config.module.
 */

/**
 * Implements hook_mail().
 */
function contact_us_config_mail($key, &$message, $params) {
    // format body base from the email template
    if ($key == 'contact_us') {
        $email_template = \Drupal::config('contact_us_config.contact_us_configuration')->get('email_template');

        $subject = html::escape($params['subject']);
        $email = html::escape($params['email']);
        $firstName = html::escape($params['firstname']);
        $lastName = html::escape($params['lastname']);
        $from = html::escape($message['reply-to']);
        $userName = Html::escape($params['username']);
        $product = Html::escape($params['product']);
        $body = Html::escape($params['body']);

        $message['subject'] = $subject;
        $message['headers']['From'] = "$firstName $lastName <$from>";

        $messageBody = str_replace([
            '@firstname',
            '@lastname',
            '@username',
            '@email',
            '@product',
            '@subject',
            '@message',
            '@date',
            '@ip',
            '@language'
        ], [
            $firstName,
            $lastName,
            $userName,
            $email,
            $product,
            $subject,
            $body,
            format_date($params['date'], 'long'),
            $params['ip'],
            $message['langcode'],
        ], $email_template);

        $message['body'][] = $messageBody;
    }
}

/**
 * Implements hook_webcomposer_form_validation_alter().
 *
 * Contact Us form - validations
 */
function contact_us_config_webcomposer_form_validation_alter(&$validations) {
  $validations['invalid_words'] = [
    'title' => 'Invalid Words',
    'description' => 'Validation to disallow specific words in the field',
    'error' => 'Invalid/not allowed characters',
    'parameters' => [
      'invalid_words_list' => [
        '#title' => 'Invalid Words List',
        '#description' => 'List of words to disallow',
        '#type' => 'textarea',
      ],
    ],
  ];
  $validations['valid_languages'] = [
    'title' => 'Valid Languages',
    'description' => 'Validation to allow or disallow specific languages based on regex value',
    'error' => "This field only accepts specific characters.",
    'parameters' => [
      'regex_value' => [
        '#title' => 'Regex String',
        '#description' => 'Regex value that will be tested on the front end. ' .
          '(Only configure this if you know how to code a regex)',
        '#type' => 'textarea',
      ],
    ],
  ];
}
