<?php

/**
 * Implements hook_uninstall
 */
function webcomposer_games_statuses_uninstall() {
  $keys = [
		'field.field.node.games.field_disable_in_tablet',
		'field.field.node.games.field_preview_display_only',
		'field.field.node.games.field_status',
		'field.storage.node.field_disable_in_tablet',
		'field.storage.node.field_preview_display_only',
		'field.storage.node.field_status'
  ];

  foreach ($keys as $key) {
    \Drupal::configFactory()->getEditable($key)->delete();
  }
}
