<?php
/**
 * @file
 * Containsdesktop_slider.module. */use Drupal\Core\Routing\RouteMatchInterface;/**
 * Implements hook_help().
 */
function desktop_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for thedesktop_slider module.
    case 'help.page.desktop_slider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Desktop Slider') . '</p>';
      return $output;

    default:
  }
}