<?php

/**
 * @file
 * Contains registration_theme.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function registration_theme_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the registration_theme module.
    case 'help.page.registration_theme':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Themeable Registration Configuration') . '</p>';
      return $output;

    default:
  }
}

// function registration_theme_theme() {
//   return [
//     'registration_theme' => [
//       'render element' => 'children',
//     ],
//   ];
// }
