<?php

/**
 * @file
 * Contains webcomposer_domain_import.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webcomposer_domain_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_domain_import module.
    case 'help.page.webcomposer_domain_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module take care of domiain import and export.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function webcomposer_domain_import_theme() {
  return [
    'webcomposer_domain_import' => [
      'template' => 'webcomposer_domain_import',
      'render element' => 'children',
    ],
  ];
}
