<?php

/**
 * @file
 * Contains ghana_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ghana_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ghana_config module.
    case 'help.page.ghana_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ghana Configuration') . '</p>';
      return $output;

    default:
  }
}
