<?php

/**
 * @file
 * Contains zipang_canonical.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zipang_canonical_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zipang_canonical module.
    case 'help.page.zipang_canonical':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Zipang Canonical') . '</p>';
      return $output;

    default:
  }
}
