<?php

/**
 * @file
 * Contains webcomposer_cdn.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_inline_image_url_change_alter().
 */
function webcomposer_cdn_inline_image_url_change_alter(&$uri, $base_path, $path) {
  // Get the CDN configuration from the.
  $config = \Drupal::config('webcomposer_config.cdn_configuration');
  $cdn_is_enabled = $config->get('enable_cdn');
  $cdn_domains = $config->get('cdn_domain_configuration');

  if (isset($_SERVER['HTTP_X_FE_COUNTRY_CODE'])) {
    $country_code = $_SERVER['HTTP_X_FE_COUNTRY_CODE'];
  } else {
    $country_code = NULL;
  }

  // Get domain configuration in the form of array.
  $domains = explode(PHP_EOL, $cdn_domains);

  foreach ($domains as $value) {
    $domain_value = str_replace(' ', '', $value);
    list($code, $domain) = explode('|', $domain_value);
    $domain_settings[$code] = $domain;
  }

  // Alter the image url if the request is from front-end.
  if (isset($_SERVER['HTTP_X_FE_BASE_URI']) &&
    $cdn_is_enabled === 1 &&
    !empty($country_code) &&
    array_key_exists($country_code, $domain_settings)
  ) {
    $uri = "[uri:($path)]";
  }
}
