<?php

/**
 * @file
 * Contains mobile_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mobile_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mobile_config module.
    case 'help.page.mobile_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module for mobile specific updates') . '</p>';
      return $output;

    default:
  }
}

function mobile_config_form_webcomposer_config_schema_form_base_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if ($form['#editable_config_names'][0] == 'webcomposer_config.header_configuration') {
      $form['login_group']['mobile_remember'] = [
        '#type' => 'textfield',
        '#title' => 'Remember Username Text',
        '#description' => 'Remember username text for login lightbox.',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.header_configuration', 'mobile_remember') ?? 'Remember Username',
        '#required' => TRUE,
        '#translatable' => TRUE
      ];

      $form['login_group']['mobile_login_reg'] = [
        '#type' => 'textfield',
        '#title' => 'Login and Registration Button Text',
        '#description' => 'Combination field for Login and Registration',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.header_configuration', 'mobile_login_reg') ?? 'Join Now',
        '#required' => TRUE,
        '#translatable' => TRUE
      ];

      $form['header_other_group']['mobile_slot_title'] = [
        '#type' => 'textfield',
        '#title' => 'Slots - Lobby Page Title.',
        '#description' => 'Slots Lobby Page Title.',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.header_configuration', 'mobile_slot_title') ?? '',
        '#required' => TRUE,
        '#translatable' => TRUE,
      ];

      $form['header_other_group']['mobile_live_dealer_title'] = [
        '#type' => 'textfield',
        '#title' => 'Live Dealer - Lobby Page Title.',
        '#description' => 'Live Dealer Lobby Page Title.',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.header_configuration', 'mobile_live_dealer_title') ?? '',
        '#required' => TRUE,
        '#translatable' => TRUE,
      ];

      $form['header_other_group']['mobile_arcade_title'] = [
        '#type' => 'textfield',
        '#title' => 'Arcade - Lobby Page Title.',
        '#description' => 'Arcade Lobby Page Title.',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.header_configuration', 'mobile_arcade_title') ?? '',
        '#required' => TRUE,
        '#translatable' => TRUE,
      ];

      $form['logo_group']['logo_title_slots'] = [
        '#type' => 'textfield',
        '#title' => 'Slots - Logo Title.',
        '#description' => 'Slots Logo Title.',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.header_configuration', 'logo_title_slots') ?? '',
        '#required' => TRUE,
        '#translatable' => TRUE,
      ];

        $form['logo_group']['logo_title_live_dealer'] = [
        '#type' => 'textfield',
        '#title' => 'Live Dealer - Logo Title.',
        '#description' => 'Live Dealer Logo Title.',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.header_configuration', 'logo_title_live_dealer') ?? '',
        '#required' => TRUE,
        '#translatable' => TRUE,
      ];

      $form['logo_group']['logo_title_arcade'] = [
        '#type' => 'textfield',
        '#title' => 'Arcade - Logo Title.',
        '#description' => 'Arcade Logo Title.',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.header_configuration', 'logo_title_arcade') ?? '',
        '#required' => TRUE,
        '#translatable' => TRUE,
      ];
    }

    if ($form['#editable_config_names'][0] == 'webcomposer_config.footer_configuration') {
      $form['mobile_footer'] = [
        '#type' => 'details',
        '#title' => 'Mobile Footer Menu',
        '#collapsible' => TRUE,
        '#group' => 'advanced'
      ];

      $form['mobile_footer']['mobile_language_select'] = [
        '#type' => 'textfield',
        '#title' => 'Select Language Text',
        '#description' => 'Select Language text for language lightbox.',
        '#default_value' => \Drupal::service('webcomposer_config_schema.schema')->getConfigValue('webcomposer_config.footer_configuration', 'mobile_language_select') ?? 'Select Language',
        '#translatable' => TRUE
      ];
    }
}
