<?php

/**
 * @file
 * Contains reset_password.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_webcomposer_form_validation_alter().
 *
 * Reset Password form - Password validation
 */
function reset_password_webcomposer_form_validation_alter(&$validations) {
  // confirm password validation
  $validations['match_password'] = [
    'title' => 'Validate password to be match',
    'description' => 'Validation for password if match',
    'error' => 'Password not match',
  ];

  $validations['not_match_username'] = [
    'title' => 'Not Match Username',
    'description' => 'Validation to disallow current username as password',
    'error' => 'Password should not equal to username',
  ];
}