<?php

/**
 * @file
 * Contains webcomposer_catchpoint.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webcomposer_catchpoint_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webcomposer_catchpoint module.
    case 'help.page.webcomposer_catchpoint':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module take care of Catchpoint configuration.') . '</p>';
      return $output;

    default:
  }
}
