<?php
  /**
  * @file
  * Contains webcomposer_faqs_configuration.module.
  */
  use Drupal\Core\Routing\RouteMatchInterface;
  /**
  * Implements hook_help().
  */
function webcomposer_faqs_configuration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for thewebcomposer_faqs_configuration module.
    case 'help.page.webcomposer_faqs_configuration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Faqs Configuration Module') . '</p>';
      return $output;

    default:
  }
}